import Link from "next/link";
import { contentTypes, posts, resources } from "@/lib/content";

export default function Home() {
  return <div className="page">
    <section className="hero"><div><p className="eyebrow">EARLY-STAGE COMPANIES</p><h1>Why do some early-stage companies <em>struggle to grow?</em></h1></div><div className="hero-aside"><p>I’m Omoseebi Vincent.</p><p>I’m trying to understand what actually keeps early-stage companies from moving forward — whether the problem is the customer, the product, the positioning, the marketing, the sales process, or something else entirely.</p><p>I study the problem before jumping to the solution, test what I believe, and document what I learn.</p><Link className="arrow-link" href="/blog">Read my thinking →</Link> <Link className="arrow-link" href="/about">About me →</Link></div></section>
    <section className="section"><p className="eyebrow">THE QUESTION</p><h2>Your growth problem might not be the problem you think it is.</h2><div className="copy-columns"><div><p>A founder can say:</p><p>“We need more customers.”</p><p>But that doesn’t tell us what is actually wrong.</p></div><div><p>Maybe the problem is that the wrong people are being targeted.</p><p>Maybe the product solves a problem people don’t care enough about. Maybe the value isn’t clear. Maybe the positioning is wrong.</p><p>Maybe customers are interested but don’t convert. Maybe the company can acquire customers but can’t retain them. Maybe the product is fine and distribution is the constraint.</p><p>Or maybe we simply don’t know yet.</p><p>That is the part I’m interested in.</p></div></div><p className="closing-line">Not jumping to the answer.<br />Figuring out what is actually happening.</p><p className="eyebrow">Understand first. Validate second. Build third.</p></section>
    <section className="section method"><div><p className="eyebrow">WHAT I’M DOING</p><h2>I’m learning how to figure that out.</h2></div><div><p className="method-lead">I’m building the skills to move from:</p><p className="workflow">observation → understanding → problem identification → hypothesis → experiment → evidence → decision → building.</p><p>Then learning from what happens.</p><p className="small-copy">That means learning about customer discovery, product thinking, positioning, marketing, distribution, sales, retention, experimentation, and building.</p><p className="small-copy">Not because I want to collect frameworks. Because I want to become better at understanding real problems.</p></div></section>
    <section className="section"><div className="section-head"><div><p className="eyebrow">THINKING IN PUBLIC</p><h2>What I’m learning along the way.</h2></div><Link className="arrow-link" href="/blog">Read the writing →</Link></div><p className="section-intro">This is where I document the things I notice, questions I’m investigating, experiments I run, research I do, and lessons that change how I think.</p><p className="section-intro">Some ideas will be right. Some will be wrong. Some will change. That is the point.</p><div className="post-grid">{posts.slice(0, 3).map((post) => <Link className="post" href={`/blog/${post.slug}`} key={post.slug}><span className="tag">[{post.type}]</span><h3>{post.title}</h3><p>{post.excerpt}</p><span className="meta">{post.number ?? "—"} · {post.date} · {post.topic}</span></Link>)}{posts.length === 0 && <p className="empty-state">The writing archive will hold observations, hypotheses, experiments, research, essays, lessons, and notes as they are published.</p>}</div></section>
    <section className="section"><p className="eyebrow">HOW I DOCUMENT THE WORK</p><h2>Six ways of thinking through the work.</h2><div className="method-copy content-types">{contentTypes.map((type) => <div className="method-step" key={type}><span className="label">{type}</span><p>{type === "Observation" && "Things I notice that make me stop and ask a question."}{type === "Hypothesis" && "Things I currently believe might be true."}{type === "Experiment" && "Things I test to find out whether they are true."}{type === "Research" && "Things I investigate to understand a problem better."}{type === "Essay" && "Longer attempts to think carefully about a problem or idea."}{type === "Lesson" && "Things that changed my mind."}{type === "Note" && "Shorter ideas, questions, and unfinished thinking."}</p></div>)}</div></section>
    <section className="section"><div className="section-head"><div><p className="eyebrow">TOOLS FOR THE WORK</p><h2>Things I build to make the thinking useful.</h2></div><Link className="arrow-link" href="/resources">Explore resources →</Link></div><p className="section-intro">Some of the things I learn will become practical resources — worksheets, checklists, frameworks, guides, and other tools that can help someone work through a problem themselves.</p>{resources.length > 0 ? <div className="resource-strip">{resources.map((resource) => <Link className="resource" href={`/resources/${resource.slug}`} key={resource.slug}><span className="tag">{resource.type} / {resource.access}</span><h3>{resource.title}</h3><p>{resource.description}</p></Link>)}</div> : <p className="empty-state">Resources will appear here as practical outputs from the work.</p>}</section>
    <section className="section"><p className="eyebrow">ABOUT</p><h2>I’m not here with all the answers.</h2><div className="copy-columns"><div><p>I’m still figuring things out.</p><p>I’m learning how to understand customers better, identify real problems, test assumptions, build useful products, and figure out what actually makes an early-stage company move forward.</p></div><div><p>This website is part of that process.</p><p>It is where I document the questions, the research, the experiments, the mistakes, and the things I learn along the way.</p><Link className="arrow-link" href="/about">More about me →</Link></div></div></section>
    <section className="section"><div className="newsletter"><p className="eyebrow">STAY CLOSE</p><h2>Follow what I’m figuring out.</h2><p>Occasional notes on what I’m learning about customers, products, founders, and early-stage growth.</p><p>No generic startup motivation. Just the ideas, experiments, and lessons worth sharing.</p><form className="newsletter-form"><input aria-label="Email address" type="email" placeholder="your@email.com" /><button type="submit">GET THE NOTES →</button></form></div></section>
  </div>;
}
