import Link from "next/link";
import { posts, resources } from "@/lib/content";

export default function Home() {
  return <div className="page">
    <section className="hero"><div><p className="eyebrow">FIELD NOTES // 001</p><h1>Why isn’t your company growing the way <em>you expected?</em></h1></div><div className="hero-aside"><p>I’m Omoseebi Vincent. I’m studying the problems that prevent early-stage companies from scaling, and documenting what I observe, test, build, and learn.</p><Link className="arrow-link" href="/about">Read the working thesis ↗</Link></div></section>
    <section className="section"><div className="section-head"><h2>Recent notes</h2><span className="eyebrow section-index">01 / Blog</span></div><div className="post-grid">{posts.map((post) => <Link className="post" href={`/blog/${post.slug}`} key={post.slug}><span className="tag">[{post.type}]</span><h3>{post.title}</h3><p>{post.excerpt}</p><span className="meta">{post.number} · {post.date} · {post.topic}</span></Link>)}</div></section>
    <section className="section method"><h2>Understand first.<br />Validate second.<br /><em>Build third.</em></h2><div className="method-copy"><div className="method-step"><span className="label">01 / Observation</span><strong>Notice what is happening.</strong><p>Start with the behaviour, friction, or pattern in front of us.</p></div><div className="method-step"><span className="label">02 / Hypothesis</span><strong>Name what might be true.</strong><p>Make the assumption explicit enough to examine.</p></div><div className="method-step"><span className="label">03 / Experiment</span><strong>Test the smallest useful thing.</strong><p>Prefer evidence over eloquence. Learn before scaling.</p></div><div className="method-step"><span className="label">04 / Learning</span><strong>Let the result change the plan.</strong><p>Capture what changed, including what did not work.</p></div></div></section>
    <section className="section"><div className="section-head"><h2>Useful instruments</h2><Link className="arrow-link" href="/resources">View all resources ↗</Link></div><div className="resource-strip">{resources.map((resource) => <Link className="resource" href={`/resources/${resource.slug}`} key={resource.slug}><span className="tag">{resource.type} / {resource.access}</span><h3>{resource.title}</h3><p>{resource.description}</p></Link>)}</div></section>
    <section className="section"><div className="newsletter"><h2>A short dispatch when there is something worth examining.</h2><form className="newsletter-form"><input aria-label="Email address" type="email" placeholder="your@email.com" /><button type="submit">JOIN ↗</button></form></div></section>
  </div>;
}
